### ISSUE TITLE
What to do with HWID URLs

### ISSUE THREAD

**Issue by buiawpkgew1** [V1li/hwid#1]

**Comment by buiawpkgew1** [comment]
Can you do it on GitHub?

**Comment by HerraVp** [comment]
For example: https://vp-dev.eu/json/hwid.json

And yes, I think you can do it using Github.

**Comment by buiawpkgew1** [comment]
> 例如：[vp-dev.eu/json/hwid.json](https://vp-dev.eu/json/hwid.json)
> 
> 是的，我认为你可以使用Github做到这一点。

Do you have an indication?

**Comment by buiawpkgew1** [comment]
> 例如：[vp-dev.eu/json/hwid.json](https://vp-dev.eu/json/hwid.json)
> 
> 是的，我认为你可以使用Github做到这一点。

![image](https://user-images.githubusercontent.com/71136405/184494396-5e3e8146-a2a7-40a0-a44d-1637f3ffe5d2.png)
is this OK? ?

**Comment by HerraVp** [comment]
Yes, that should world fine.

**Comment by buiawpkgew1** [comment]
Can the test be changed at will?

**Comment by buiawpkgew1** [comment]
[            embed.setThumbnail("https://cdn.discordapp.com/attachments/986653004356812880/997177199029395576/yawn.png");](https://github.com/HerraVp/hwid/blob/1bef1f8fb600b2b19f1ed42301654c8f3e03910e/src/main/java/hwid/Hwid.java#L53)
Do you want to modify here?

**Comment by HerraVp** [comment]
You can uncomment the `System.out.println(hwid);` line to get your systems hwid. Then you can replace the example values from the hwid.json file with your own hwid.


> [ embed.setThumbnail("https://cdn.discordapp.com/attachments/986653004356812880/997177199029395576/yawn.png");](https://github.com/HerraVp/hwid/blob/1bef1f8fb600b2b19f1ed42301654c8f3e03910e/src/main/java/hwid/Hwid.java#L53) Can it be modified here?

And you can change that to whatever you want, or remove it completely. Its just an image for the Discord webhook.

**Comment by buiawpkgew1** [comment]
How to add i18n?

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/184495242-4e4a7e14-c0ab-48cf-b04f-5f623a5ffdd6.png)
![image](https://user-images.githubusercontent.com/71136405/184495251-4e077d90-c3df-4ef4-9be1-2eb5da84f495.png)
is that so

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/184495379-5b9b9ffe-c6fe-4904-b496-7144ec994b34.png)

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/184495503-007f2029-3596-4a2a-92b5-5d9ce018d2c6.png)

**Comment by HerraVp** [comment]
The url in the code has to end with `?hwid=`.

So in your case the url is: `https://raw.githubusercontent.com/buiawpkgew1/HWID/main/hwid.json?hwid=`

**Comment by buiawpkgew1** [comment]
thanks

**Comment by buiawpkgew1** [comment]
How does the Discord webhook work?

            Webhook webhook=new Webhook("https://discord.com/api/webhooks/1007984093935435796/xxxxxxxxxxxxxxxxxxx");

**Comment by buiawpkgew1** [comment]
Why can't other people find hwid code

**Comment by buiawpkgew1** [comment]
Add hwid, and then multiple people and single people can't go in

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/184852813-f9fb79ad-8639-4223-a94c-7fbf87b379a4.png)
How to get "beginning"
